[workspace]

members = [
  "tokio",
  "tokio-macros",
  "tokio-test",
  "tokio-util",
  "tokio-hello-world-leak",

  # Internal
  "benches",
  "examples",
  "tests-build",
  "tests-integration",
]
[patch.crates-io]
tokio = { path = "tokio" }
tokio-macros = { path = "tokio-macros" }
tokio-test = { path = "tokio-test" }
tokio-util = { path = "tokio-util" }